version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d imagevault" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - 'POSTGRES_DB=imagevault'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2025-04-03T14-56-28Z
    container_name: minio_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  api:
    build: .
    container_name: imagevault_api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
  minio-data: